### ISSUE TITLE
Error executing 'postInstallation': mysqlCore.checkConnection is not a function

### ISSUE THREAD

**Issue by unrl** [bitnami/bitnami-docker-joomla#13]
Hi,

i'm getting the following error, when i try to start the joomla container. Tried manually and with compose, always the same problem. I noticed that the function needs a database, which cannot be set according to your envirnonment variable definition.

Error:
Error executing 'postInstallation': mysqlCore.checkConnection is not a function

**Comment by prydonius** [comment]
Looks like the same issue as #11. Have you tried running `docker pull bitnami/joomla` or specifically trying the `bitnami/joomla:3.6.2-r1` tag?

**Comment by unrl** [comment]
Oops, i forgot to look into the closed ones... But i pulled right now and the error is still there..

**Comment by unrl** [comment]
Thanks for your support, bitnami/joomla:3.6.2-r1 is working nicely. I pulled master and latest before, both gave me the same issue.

**Comment by prydonius** [comment]
Thanks for checking @unrl, it's strange - `latest` should be pointing to `3.6.2-r1`. I'll take a look to ensure those tags are correct.

**Comment by prydonius** [comment]
Could it have been a caching issue on your side? I was able to get it working successfully using the `latest` tag in a clean Docker environment.

**Comment by unrl** [comment]
Seems like i have missed the latest by a couple of minutes. It works now.
