### ISSUE TITLE
Failed to connect to mariadb:3306

### ISSUE THREAD

**Issue by Badisi** [bitnami/bitnami-docker-joomla#2]
Mac OSX Yosemite 10.10.5
Docker for Mac 1.12.0-rc2-beta17 (build: 9779)
Kitematic 0.12.0

Trying to install the bitnami-joomla container through kitematic will result in the following error:
```
harpoon INFO  Initializing php   
harpoon INFO  php successfully initialized   
harpoon INFO  Initializing apache   
harpoon INFO  apache successfully initialized   
harpoon INFO  Initializing joomla   
handler INFO  Trying to connect to MySQL server   
Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries
```

Also, trying to start mysql from the container will throw this error:
```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2 "No such file or directory")
```

Thanks for your help :-)

**Comment by chipironcin** [comment]
Hi @Badisi 
Have you started the MariaDB container too?
This image contains the Joomla app with Apache+PHP to serve the requests, but the database should be in another container.
You can use docker-compose to ease the container link process, check the README.md at https://github.com/bitnami/bitnami-docker-joomla#user-content-how-to-use-this-image

Hope it helps, tell us if you reach some unexpected error while following the instructions or if you have any other question ;)

**Comment by prydonius** [comment]
Just to add to @chipironcin's comments, Kitematic doesn't support Docker Compose, and so to correctly use this Joomla container, you will need to use the Docker Compose CLI. You can read more about Docker Compose in Docker's documentation: https://docs.docker.com/compose/

**Comment by Badisi** [comment]
Hi @chipironcin 
Using docker-compose in CLI did help in my case. Thanks a lot!
I was a little bit confused because I thought Kitematic would use the *docker-compose.yml* file (but it seems not). Also I was previously using the bitnami native installer for joomla and everything was bundled in there so I was expecting this docker container to do the same.
Maybe it can help others to explain in the readme that the mariadb is in fact a separate container.
Anyway thanks again ;)

**Comment by prydonius** [comment]
Thanks @Badisi, we will try to make this clearer in the documentation!

**Comment by Badisi** [comment]
Hi @prydonius, may I ask you 2 more questions please (I'm not having any help from the forum..):
1) Neither this container nor the mariadb container has phpmyadmin
How could I install it myself ? The dockerfile has a bitnami-pkg to install or unpack stuff but where can I find the phpmyadmin package ?
2) How can we change the name of the db ? (default is bitnami_joomla)
Thanks a lot for your help!

**Comment by chipironcin** [comment]
Hi @Badisi 
I am glad you could start the Joomla application!
I will try to answer your questions:
  1. We did not include PHPMyAdmin as it is not required to run Joomla. In the near future, we may package it as a single module with its own Dockerfile or allow you to enable it in the MariaDB container. Meanwhile, you can launch an already built PHPMyAdmin pointing to the database IP address and with the root user and password (i.e.  https://hub.docker.com/r/phpmyadmin/phpmyadmin/). Stay tuned to https://github.com/bitnami
  2. The name of the database is configured internally from `bitnami-pkg install` and at the moment it isn't configurable

**Comment by shershen08** [comment]
I was having the same 
: `Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries`
![screen shot 2017-02-27 at 16 28 36](https://cloud.githubusercontent.com/assets/1363772/23367257/e2be27e8-fd09-11e6-920e-1025c1de0e99.png)

While using Kinematic, but then switched to Docker CLI, like's stated in the readme:
```
$ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-joomla/master/docker-compose.yml
$ docker-compose up
```
and it works fine!
