### ISSUE TITLE
problem after docker down / up joomla ( joomla  INFO  [retry] Trying to configure permissions)

### ISSUE THREAD

**Issue by edv-admin** [bitnami/bitnami-docker-joomla#45]
(nearby) latest versions from today :-)

adminazure@ubuntu01:~/joomla-docker-compose$ docker-compose down
Stopping joomladockercompose_joomla_1 ... done
Stopping joomladockercompose_mariadb_1 ... done
Removing joomladockercompose_joomla_1 ... done
Removing joomladockercompose_mariadb_1 ... done
Removing network joomladockercompose_default
adminazure@ubuntu01:~/joomla-docker-compose$ docker-compose up
Creating network "joomladockercompose_default" with the default driver
Creating joomladockercompose_mariadb_1
Creating joomladockercompose_joomla_1
Attaching to joomladockercompose_mariadb_1, joomladockercompose_joomla_1
mariadb_1  | nami    INFO  Initializing mariadb
mariadb_1  | mariadb INFO
mariadb_1  | mariadb INFO  ########################################################################
mariadb_1  | mariadb INFO   Installation parameters for mariadb:
mariadb_1  | mariadb INFO     Persisted data and properties have been restored.
mariadb_1  | mariadb INFO     Any input specified will not take effect.
mariadb_1  | mariadb INFO   (Passwords are not shown for security reasons)
mariadb_1  | mariadb INFO  ########################################################################
mariadb_1  | mariadb INFO
mariadb_1  | nami    INFO  mariadb successfully initialized
mariadb_1  | Starting application ...
mariadb_1  |
mariadb_1  |   *** Welcome to the mariadb image ***
mariadb_1  |   *** Brought to you by Bitnami ***
mariadb_1  |   *** More information: https://github.com/bitnami/bitnami-docker-mariadb ***
mariadb_1  |   *** Issues: https://github.com/bitnami/bitnami-docker-mariadb/issues ***
mariadb_1  |
joomla_1   | nami    INFO  Initializing apache
joomla_1   | apache  INFO  ==> Reconfiguring PID file location...
joomla_1   | nami    INFO  apache successfully initialized
mariadb_1  |
mariadb_1  | *** New version available: run docker pull bitnami/mariadb:10.1.21-r0 to update. ***
mariadb_1  |
joomla_1   | nami    INFO  Initializing php
joomla_1   | nami    INFO  php successfully initialized
mariadb_1  | 2017-01-19 17:02:59 140432548366208 [Note] InnoDB: Highest supported file format is Barracuda.
mariadb_1  | 2017-01-19 17:02:59 140432548366208 [Note] InnoDB: 128 rollback segment(s) are active.
mariadb_1  | 2017-01-19 17:02:59 140432548366208 [Note] InnoDB: Waiting for purge to start
mariadb_1  | 2017-01-19 17:02:59 140432548366208 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.34-79.1 started; log sequence number 28904671
mariadb_1  | 2017-01-19 17:02:59 140431996221184 [Note] InnoDB: Dumping buffer pool(s) not yet started
mariadb_1  | 2017-01-19 17:02:59 140432548366208 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1  | 2017-01-19 17:02:59 140432548366208 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1  | 2017-01-19 17:02:59 140432548366208 [Warning] 'proxies_priv' entry '@% root@bb495c497e3b' ignored in --skip-name-resolve mode.
mariadb_1  | 2017-01-19 17:02:59 140432548366208 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1  | Version: '10.1.20-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
joomla_1   | nami    INFO  Initializing joomla
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 19 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 18 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 17 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 16 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 15 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 14 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 13 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 12 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 11 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 10 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 9 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 8 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 7 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 6 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 5 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 4 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 3 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 2 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 1 remaining attempts
joomla_1   | joomla  INFO  [retry] Trying to configure permissions... 0 remaining attempts
joomla_1   | Error executing 'postInstallation': ENOENT: no such file or directory, chown '/bitnami/joomla/images/Agenda_Praxisseminar_Zugangser+ï¿½ffnung_Ersetzendes_Scannen_Region_WEST.png'

**Comment by prydonius** [comment]
Thanks @edv-admin, we're looking into this. From a quick look, it might be an issue with the special characters in that filename (`'/bitnami/joomla/images/Agenda_Praxisseminar_Zugangser+ï¿½ffnung_Ersetzendes_Scannen_Region_WEST.png'`). We'll take a deeper look and let you know what we find.

**Comment by edv-admin** [comment]
i think so 
here some pictures for joomla/images with german umlauts for testing

[testpics_with_german_chars.zip](https://github.com/bitnami/bitnami-docker-joomla/files/719177/testpics_with_german_chars.zip)

**Comment by sameersbn** [comment]
@edv-admin can you share some information regarding your setup? are you using docker for mac, docker-machine, etc?

I tried this case with docker on ubuntu host and it worked fine with the  filenames you specified.

**Comment by sameersbn** [comment]
also can you share the docker-compose.yml and the web browser you are using?
I tried using chrome and FF and both seem to strip away the german characters from the filenames.

**Comment by edv-admin** [comment]
system:  docker on ubuntu16.04 LTS - Browser Firefox/Waterfox Windows 8/10

version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    restart: always
    volumes:
      - '/docker-home/joomla/mariadb:/bitnami/mariadb'
  joomla:
    image: 'bitnami/joomla:latest'
    restart: always
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/docker-home/joomla/joomla:/bitnami/joomla'
      - '/docker-home/joomla/apache:/bitnami/apache'
      - '/docker-home/joomla/php:/bitnami/php'


i thing, the wrong filenames are from older joomla versions (on a "real" server) -> backup/restore with akeeba.  after replacing the "wrong" files/filenames a restart works fine
for this, the ticket can be closed - thanks for support

btw. PHP seems to be an old Version 5.2.6 - is there an update to v 7.x planned?

**Comment by juan131** [comment]
@edv-admin regarding PHP. In this moment we use PHP 5.6.30. However we're considering moving to PHP 7.x.x. We'll let you know if we decided to move to it. 
I opened this new issue to discuss it. https://github.com/bitnami/bitnami-docker-joomla/issues/48
We'll continue the discussion there closing this issue.
