### ISSUE TITLE
restored volume prevents container execution

### ISSUE THREAD

**Issue by hubsi** [bitnami/bitnami-docker-joomla#59]
**Steps to reproduce the issue:**
1. mount /var/lib/docker/volumes to persistent location (surviving docker host and container rebuild)
2. rebuild docker host (optional)
3. recreate container with attached volume (from persistent location)

**Describe the results you received:**

docker container exits

docker ps -a
CONTAINER ID        IMAGE                                                                      COMMAND                  CREATED              STATUS                            PORTS               NAMES
69ba99589139        bitnami/joomla:latest                                                      "/app-entrypoint.s..."   46 seconds ago       Exited (5) 43 seconds ago                             bitnami_joom
docker logs 69ba99589139
[...]
nami    ERROR com.bitnami.apache is not fully installed. You cannot execute commands

**Describe the results you expected:**

container should successfully run using data from restored volume. 

How is an automatic backup/restore workflow supposed to happen (step by step)?
Is the following the only way to use this docker image with a data restore? 
   1. create container
   2. stop container
   3. copy/rsync snapshot data into container
   4. restart previously created container

if yes, how would you automate that? 

**Additional information you deem important (e.g. issue happens only occasionally):**

had to enable NAMI_DEBUG=1 and BASH_DEBUG=0 to see any output at all. error output should be the default behavior

creating an additional image using
FROM bitnami/joomla:latest

RUN bitnami-pkg unpack apache-2.4.27-0 --checksum 27b8591b6564856428e2a3480949d549316e2f7e5bd207faa7b8c6e3a9bb9cc0; nami install --force /tmp/bitnami/pkg/install/apache-2.4.27-0-linux-x64-debian-8

will not fix the issue, because it will overwrite user data (httpd.conf)

**Version**

- Output of `docker version`:
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.1-ce
 Built:        Tue May 30 17:59:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.1-ce
 Built:        Tue May 30 17:59:44 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
tested on AWS ECS

**Comment by sameersbn** [comment]
While we will try our best to handle your query, I would like to note that your question is related to docker host migration and not specific to the bitnami/joomla container image. For quicker resolution you should probably direct your query at the https://github.com/moby/moby project.

To understand correctly,  you:

1. are migrating your existing docker containers to a new host.
2. have mounted a disk at `/var/lib/docker/volumes`
3. copied over the contents of `/var/lib/docker/volumes/` to the new host
4. re-create the containers on the new host by specifying the existing volumes from `/var/lib/docker/volumes/`

Is this correct? Are you specifying the `--volume` arg while starting the containers on the new host? or are you expecting docker to automagically pick the existing volumes from `/var/lib/docker/volumes/`?

If your query is specific to migrating docker to a new host then moving the entire `/var/lib/docker` directory to the new host is all you really need. However there are some precautions that one should take while doing this. My recommendations are:

1. remove docker or disable docker startup
2. reboot the docker host to ensure docker is not started
3. as `root` use `rsync -a` to copy the contents of `/var/lib/docker` to the new host 
4. install docker on the new host
5. docker should have been migrated to the new host

**Comment by hubsi** [comment]
I want to thank you for providing these docker images, it is very easy to bring up a joomla installation that way for a quick test setup of joomla. Unfortunately data restore/migration seems to be not well tested, I have also found out that the used bitnami mariadb image will delete the database when trying to recreate/restore it with an attached volume. For productive use I have now moved to the official joomla docker hub image, because it supports an automatic restore process.

My question was specific to persisting the application based on this docker image, as described on the bitnami image main page, particularly at https://github.com/bitnami/bitnami-docker-joomla#persisting-your-application. Apparently the process of restoring the application was not taken into account for a container rebuild.

You understand the steps correctly, though I am not doing these steps manually and the volumes are "automagically" remounted based on the docker compose / ECS definition I adapted for use with the AWS ECS-CLI. But I also encountered issues when I manually remounted the volume using -v.

I am also not setting up docker hosts manually as described in your steps - I am using cloudformation templates with autoscaling groups and launch configurations to do this automatically. I am not looking for a solution to migrate the whole docker environment, because I need to keep the installation of the docker environment separate from the restore of the application data to support upgrades of the docker environment and also because the maintenance of docker is done at the AMI level. The steps you describe are not feasible for automating the process of setting up a fresh docker container automatically in AWS.

I am not expecting the image to be fully supported by AWS (I had to adapt the docker compose file which is ok) but a restore with volumes attached also did not work in a local docker environment.

**Comment by sameersbn** [comment]
@hubsi Sorry for the lateness of my response.

The complete state of the container is saved in the `/bitnami` directory of the container. As long as you backup/restore the entire contents of the directory, the operation should work properly.  Are you mounting the container volume at `/bitnami` or do you have separate volumes mounted for `/bitnami/php`, `/bitnami/apache` and `/bitnami/joomla`? If its the latter case, then you should restore all these volumes as well.

Could you please check and let me know. 

Again, I apologise for the delayed response.

**Comment by sameersbn** [comment]
@hubsi Sorry for the lateness of my response. Were you able to resolve the issue?
