### ISSUE TITLE
Multiple instance of joomla not working

### ISSUE THREAD

**Issue by selvakumarnms** [bitnami/bitnami-docker-joomla#62]
I was able to install joomla in kubernetes deployment with replica=1 successfully.
However I the replica count is more than 1 then I could not see joom instance is up and running.

Logs from joomla pods.
ami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
apache  INFO  ==> Configuring dummy certificates...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing libphp
nami    INFO  libphp successfully initialized
nami    INFO  Initializing joomla
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at joomla-mysql-service:3306
mysql-c INFO  MySQL server listening and working at joomla-mysql-service:3306
Error executing 'postInstallation': MySQL command failed to run. Error:
 ERROR 1062 (23000) at line 1: Duplicate entry '42' for key 'PRIMARY'

is there any way to tell second pod that dont create the DB as it is already created by first joomla pod.

I use single instance of mariaDB.

**Comment by juan131** [comment]
Hi @selvakumarnms 

Joomla! can't be configured with multiple replicas unless you have a NFS provider on your cluster and you configure NFS volumes (RWX) on the **Joomla!** deployment.

Apart from that, you should install the chart with 1 replicas and once Joomla! (first pod) has been initialised, scale your deployment by running:

```
$ kubectl scale --replicas=3 deployment/XXXX
``` 

| Note: substitute the placeholder XXX with the name of your Joomla! deployment.

Interesting read: https://engineering.bitnami.com/articles/scaling-wordpress-in-kubernetes.html

**Comment by selvakumarnms** [comment]
@juan131  thanks a lot for helping me to resolve this problem.
I have used nfs external provisioner and i found below error . could you help me?
mysql-c TRACE [canConnect] Connection with 'root' user is successful
mysql-c INFO  MySQL server listening and working at drupal-mysql-service:3306
drupal  DEBUG Upgrading Drupal database with drush...
drupal  TRACE [runProgram] Executing: drush updatedb
drupal  TRACE [configurePermissions] File to chown: /bitnami/drupal/themes
drupal  TRACE [configurePermissions] File to chown: /bitnami/drupal/modules
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default/files
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 19 remaining attempts
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 18 remaining attempts
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 17 remaining attempts
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 16 remaining attempts
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 15 remaining attempts
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 14 remaining attempts
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 13 remaining attempts
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 12 remaining attempts
[root@okd-master01 upstreamed]# kubectl logs drupal-drupal-94b88ff98-jfqps

rupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 3 remaining attempts
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 2 remaining attempts
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 1 remaining attempts
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 0 remaining attempts
Error executing 'postInstallation': Group '99' not found
nami    TRACE Error: Error executing 'postInstallation': Group '99' not found
    at _findGroup (/opt/bitnami/nami/node_modules/nami-utils/lib/os/user-management/find-group.js:10:11)
    at findGroup (/opt/bitnami/nami/node_modules/nami-utils/lib/os/user-management/find-group.js:37:10)
    at getGid (/opt/bitnami/nami/node_modules/nami-utils/lib/os/user-management/get-gid.js:22:25)
    at _chown (/opt/bitnami/nami/node_modules/nami-utils/lib/file/chown.js:22:33)
    at /opt/bitnami/nami/node_modules/nami-utils/lib/file/chown.js:77:7
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
    at Object.chown (/opt/bitnami/nami/node_modules/nami-utils/lib/file/chown.js:76:7)
    at Object.wrappedFn (/opt/bitnami/nami/node_modules/nami-utils/lib/function-wrapping.js:191:17)
    at _configurePermissions (/root/.nami/components/com.bitnami.drupal/lib/component.js:168:17) upstreamed]# kubectl exec -it nfs-provisioner-75574d5dd6-lxvxw sh

**Comment by juan131** [comment]
Did you find the issue when deploying the chart with 1 replica or did you find after running the scale command?

It seems it's trying to use a weird group in the permissions. Did you change any value when deploying the Joomla! chart?

> Error executing 'postInstallation': Group '99' not found
