### ISSUE TITLE
Unable to connect to MySQL database

### ISSUE THREAD

**Issue by DracoMilesX** [bitnami/bitnami-docker-joomla#64]
Hello I have tried to get this docker container running on 2 different ways:

1) Using an existing database. It does crate the tables but afterwards it gives Error Executing 'PostInstallation' and throws a connection refused on database location.

2) Using docker environment tags to make a database. It creates the new user, sets the password, makes the database and tables. But afterwards when it tries to connect again it fails with the same error as above.

My MySQL database runs on another port

**Comment by andresbono** [comment]
Thanks for submitting this issue, @DracoMilesX.

Could you please share with us the exact command or `docker-compose.yml` that you are using to run the container? Please substitute any real user/password/hostname with irrelevant placeholders.

**Comment by DracoMilesX** [comment]
Hello @andresbono this is my docker run:

docker run -d \
--name=Joomla01 \
--hostname=Joomla01 \
--memory=256M \
--memory-swap=384M \
--network=Services-Communication \
--restart=always \
-v /docker/apps/joomla:/bitnami \
-p 12201:80 \
-e JOOMLA_FIRST_NAME="first" \
-e JOOMLA_LAST_NAME="last" \
-e JOOMLA_PASSWORD="pass" \
-e JOOMLA_USERNAME="user" \
-e JOOMLA_EMAIL=mail \
-e MARIADB_HOST=192.168.1.20  \
-e MARIADB_PORT_NUMBER=12221 \
-e JOOMLA_DATABASE_NAME=dbsname \
-e JOOMLA_DATABASE_USER=user \
-e JOOMLA_DATABASE_PASSWORD=pass \
-e SMTP_HOST=mail \
-e SMTP_PORT=587 \
-e SMTP_USER=mail \
-e SMTP_PASSWORD=pass \
-e SMTP_PROTOCOL=tls \
bitnami/joomla

I have tried to replace the MARIADB and JOOMLA settings as well to allow joomla create the rest itself with just the root user and had the same issue:

-e MARIADB_HOST=192.168.1.20 \
-e MARIADB_PORT_NUMBER=12221 \
-e MARIADB_ROOT_USER=root \
-e MARIADB_ROOT_PASSWORD=pass \
-e MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_joomla \
-e MYSQL_CLIENT_CREATE_DATABASE_USER=bn_joomla \
-e ALLOW_EMPTY_PASSWORD=yes \

**Comment by andresbono** [comment]
Based on the commands that you have shared, the issue can be that you are creating a database user by specifying:
- `MYSQL_CLIENT_CREATE_DATABASE_USER=bn_joomla`
- `ALLOW_EMPTY_PASSWORD=yes`

But `JOOMLA_DATABASE_USER` is set to the value `user`. and `JOOMLA_DATABASE_PASSWORD` is set to a certain value.

Could you try again by unifying the database name, username and password specified by pairs of environment variables?

```
-e JOOMLA_DATABASE_USER=bn_joomla 
-e JOOMLA_DATABASE_PASSWORD=pass
-e JOOMLA_DATABASE_NAME= bitnami_joomla

-e MYSQL_CLIENT_CREATE_DATABASE_USER=bn_joomla
-e MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=pass
-e MYSQL_CLIENT_CREATE_DATABASE_NAME= bitnami_joomla
```

---

Apart from that, we have found that the Joomla package doesn't honor the database port when it is other than default. We'll fix it and we'll release a new version of the container.

**Comment by andresbono** [comment]
Hi @DracoMilesX, the latest releases of the container include the fix to this issue. We are going to close it.

Let us know if you find any issues with it!

**Comment by DracoMilesX** [comment]
Hi @andresbono thank you it seems to be starting up now without the postinstallation error.

Only thing I have currently is that while it starts I receive this error and when i go to the joomla page it only shows the text error

[Sun Jan 13 21:09:28.968008 2019] [ssl:warn] [pid 140] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 13 21:09:29.064762 2019] [mpm_prefork:notice] [pid 140] AH00163: Apache/2.4.37 (Unix) OpenSSL/1.1.0j PHP/7.1.26 configured -- resuming normal operations
[Sun Jan 13 21:09:29.064870 2019] [core:notice] [pid 140] AH00094: Command line: 'httpd -f /bitnami/apache/conf/httpd.conf -D FOREGROUND'

**Comment by andresbono** [comment]
Hi @DracoMilesX, that warning message shouldn't be affecting the content of the Joomla page. Could you take a screenshot of the content that is showing?

**Comment by DracoMilesX** [comment]
Hi @andresbono not really anything to screenshot it only shows the text "Error" for the rest nothing.

**Comment by andresbono** [comment]
Of course, that is not expected. Can you check the Chrome DevTools console to see any extra error messages that may appear? We need more information in order to find a solution. https://developers.google.com/web/tools/chrome-devtools/console/#opening_the_console

**Comment by DracoMilesX** [comment]
GET http://192.168.1.20:12201/favicon.ico 500 (Internal Server Error)

Did some more testing.

1. Running docker-compose works without issue.
2. Exporting the database from the docker-compose installation to my own has no effect
3. Changing the volumes so it uses a docker volume does nothing as well.

The only real difference would be that the docker-compose has this:
    labels:
      kompose.service.type: nodeport

**Comment by andresbono** [comment]
Hi @DracoMilesX, we have just found the issue and we could reproduce it. We are having the `Error` message that you are describing.

We are working on a new release of the container that will fix the issue. Once it is ready, we will let you know.

Thanks for reporting it!

**Comment by andresbono** [comment]
The new container version was released.

**Comment by DracoMilesX** [comment]
Hi @andresbono Thank you very much it is indeed working now.
