### ISSUE TITLE
Bitnami Joomla install problem: stuck on your application is being installed, please wait

### ISSUE THREAD

**Issue by smccauslin** [bitnami/bitnami-docker-joomla#65]
When installing BItnami's Joomla Docker, I get to the screen with the Bitnami logo followed by "Your application is installing, please wait."  

I have used the following to install the dockers.  All I have changed is the ports (81 and 444 are not in conflict with ports on my computer) and I have changed instances of "mariadb" to "mariadb1" and "joomla" to "joomla1"  

It is quite possible that I am not understanding the implications of changing mariadb --> mariadb1, for the container, network, and volume.  I've done this because I would like to keep the Joomla installs separate and frankly, I'm in the process of learning how everything works together. If there is away to use the same MariaDB Docker without affecting my initial Joomla instance, I am more than open to that.  I'd appreciate if anyone can enlighten me on this problem. 

Here is what I used to install Bitnami Joomla:

docker network create joomla1-tier &&
docker volume create --name mariadb1_data &&
docker volume create --name joomla1_data

docker run -d --name mariadb1 \
  -e ALLOW_EMPTY_PASSWORD=yes \
  -e MARIADB_USER=bn_joomla \
  -e MARIADB_DATABASE=bitnami_joomla \
  --net joomla1-tier \
  --restart=always \
  --volume mariadb1_data:/bitnami \
  bitnami/mariadb:latest

docker run -d --name joomla1 -p 81:80 -p 444:443 \
  -e ALLOW_EMPTY_PASSWORD=yes \
  -e JOOMLA_DATABASE_USER=bn_joomla \
  -e JOOMLA_DATABASE_NAME=bitnami_joomla \
  --net joomla1-tier \
  --restart=always \
  --volume joomla1_data:/bitnami \
  bitnami/joomla:latest

I do not receive any errors installing and no errors are indicated by Portainer once all are loaded.

Thanks

**Comment by javsalgar** [comment]
Hi,

You need to set the `MARIADB_HOST` to `mariadb1` if that's the hostname of the Database instance

**Comment by smccauslin** [comment]
Many thanks!

**Comment by smccauslin** [comment]
Sorry.  I tried this on a machine that has no installations of Docker Joomla  and it worked.  When I install it on the actual machine that already has a Docker Joomla installed, the web page continues to stall at the screen with the Bitnami logo followed by "Your application is installing, please wait."

My goal is to have a completely independent install of Joomla on the same machine with an already existing install.   Can you help?

Thanks again

**Comment by javsalgar** [comment]
What do the docker-compose logs show in this failed installation? Could it be a conflict trying to access an incorrect db?
