### ISSUE TITLE
How to enable redis/memcached?

### ISSUE THREAD

**Issue by Spunkie** [bitnami/bitnami-docker-joomla#70]
How can I use your `bitnami/redis` and `bitnami/memcached` docker containers in conjunction with `bitnami/joomla`?

I could obviously just throw a new `redis`/`memcached` service in my `docker-compose.yml` but wouldn't I still need to somehow install/enable/configure the php `redis`/`memcached` extensions in my `bitnami/joomla` image?

**Comment by carrodher** [comment]
Hi, although it is not a configuration we support by default, you can try to add the services, with the volumes and the dependencies in the docker-compose, for example implementing those changes to the _docker-compose.yaml_ present in the root of this repository:

```diff
@@ -8,6 +8,19 @@ services:
       - ALLOW_EMPTY_PASSWORD=yes
     volumes:
       - 'mariadb_data:/bitnami'
+  redis:
+    image: 'docker.io/bitnami/redis:6.0-debian-10'
+    environment:
+      - ALLOW_EMPTY_PASSWORD=yes
+      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
+    ports:
+      - '6379:6379'
+    volumes:
+      - 'redis_data:/bitnami/redis/data'
+  memcached:
+    image: 'docker.io/bitnami/memcached:1-debian-10'
+    ports:
+      - '11211:11211'
   joomla:
     image: 'docker.io/bitnami/joomla:3-debian-10'
     environment:
@@ -23,8 +36,13 @@ services:
       - 'joomla_data:/bitnami'
     depends_on:
       - mariadb
+      - redis
+      - memcached
+
 volumes:
   mariadb_data:
     driver: local
   joomla_data:
     driver: local
+  redis_data:
+    driver: local
```

Basically, it adds Redis with a volume and Memcached without volume, then we set a dependency between Joomla and those new services. This _docker-compose.yaml_ should start 4 services (Joomla, MariaDB, Redis, and Memcached).

Then you should modify the Joomla configuration file to use the desired cache system. This file is located at `/bitnami/joomla/configuration.php` and it's persisted between executions, so you need to modify the file and the stop/start the joomla container to apply the changes:
```console
$ docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                                      NAMES
362a32dd9a07        bitnami/joomla:3-debian-10       "/app-entrypoint.sh …"   10 minutes ago      Up 10 seconds       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   bitnami-docker-joomla_joomla_1
3339d2b6fc9b        bitnami/redis:6.0-debian-10      "/opt/bitnami/script…"   10 minutes ago      Up 10 seconds       0.0.0.0:6379->6379/tcp                     bitnami-docker-joomla_redis_1
65e168caaa41        bitnami/memcached:1-debian-10    "/opt/bitnami/script…"   10 minutes ago      Up 10 seconds       0.0.0.0:11211->11211/tcp                   bitnami-docker-joomla_memcached_1
1eb264dfa9de        bitnami/mariadb:10.1-debian-10   "/opt/bitnami/script…"   10 minutes ago      Up 10 seconds       3306/tcp                                   bitnami-docker-joomla_mariadb_1

$ docker-compose exec 362a32dd9a07
root@8eb9fcbf54af:/# install_packages vim
root@8eb9fcbf54af:/# vim /bitnami/joomla/configuration.php

$ docker-compose stop joomla
$ docker-compose start joomla
```

With the above commands, you can enter in the Joomla container, install `vim`, open the configuration file (edit it) and restart the Joomla container to use the modified configuration file.

About the specific changes in the configuration file, I am not an expert on Joomla administration but googling a bit I found some useful information like [this one](https://stackoverflow.com/questions/1260258/how-to-use-memcached-with-joomla).

**Comment by Spunkie** [comment]
@carrodher Thanks for the quick response, ya this is basically the setup I initially tried and was unable to get working. 

I went through and tested again with your exact setup just now, but it still doesn't work. Neither 'memcached' or 'redis' shows up as an available cache handler in the joomla global config. When I force 'redis' or 'memcached' as a cache handler by manually editing the `configuration.php` to as your suggested it just results in the site erroring out. 
___
I believe it's not working because the redis and memcached **php extensions** are not enabled in the `bitnami/joomla` container? Which is why I opened this ticket since I'm not sure how to gracefully install/enable those php extenions?

**Comment by carrodher** [comment]
Hi, I just created an internal task to evaluate the possibility of adding Redis and Memcached PHP extensions to the Joomla container image. I can't provide you an exact ETA for this task it is also possible to create a new image with the required changes by creating a new `Dockerfile` extended from the existing `bitnami/joomla`.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-joomla#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
