### ISSUE TITLE
Cannot create Azure Web App or Azure Container Instance based on Bitnami Joomla 3.9.19 Docker image

### ISSUE THREAD

**Issue by CodeOfConduct** [bitnami/bitnami-docker-joomla#71]
I successfully registered the Bitnami Joomla 3.9.19 Docker image from the Azure Market Place in an Azure Container Registry (ACR). However, after trying the different deployment options mentioned below and calling up the publication URL of the Joomla website, only the Bitnami page with the message “Your application is being installed, please wait…” was shown  and is reloaded periodically (evidently as Azure is re-trying the creation of the Web App again and again).

Steps taken: 

1)	After registering the Bitnami Docker image in the ACR, changed its Settings>Access keys>Admin user to “Enable”
2)	Initiated the creation of an Azure Web App (New resource>Web App) 
3)	Specified, under Container settings>Single Container, the Docker image source as the ACR in which I had registered the Docker image
4)	Created an Azure Database for Maria DB server 
5)	Connected to the newly created Azure Database for Maria DB host with MySQL Workbench.
6)	Created a new database (schema) on the Azure Database for Maria DB host
7)	From the Azure Database for Maria DB server copied connection string for Web App and replaced database name and password placeholders with actual values
8)	Specified in Web App under Settings>Configuration, the connection string from previous step 
9)	Restarted Web App

Expected result: creation of Joomla instance in Web App

Actual result on publication URL: Bitnami page with the message “Your application is being installed, please wait…”

Following the recommendation at https://github.com/bitnami/bitnami-docker-joomla#readme1 I tried to use docker-compose, but got the response in the Azure Cloud Shell: "bash: docker-compose: command not found", so it seems that the docker-compose command is not supported via the bash CLI in Azure (even though Docker Compose is available in Preview in the container settings of Azure Web Apps). Even if I did want to use Docker Compose in Preview, what configuration details should be entered in the Web Apps’ Configuration field under Container settings/Docker Compose (Preview)?

As this the Bitnami Joomla Docker image is offered as in the Joomla Market Place, it would be appropriate to have clear instructions on how to use it Azure, ideally in the portal, i.e. without having to resort to scripting. The official Bitnami instructions for using that image in Azure do not even mention the word Azure... (https://github.com/bitnami/bitnami-docker-joomla#readme1 - this is where the "How to use this image" link points from https://azuremarketplace.microsoft.com/en-us/marketplace/apps/bitnami.joomla-container).

**Comment by beltran-rubo** [comment]
Hi @CodeOfConduct,

There are different ways to deploy the Container in Azure. One of them is using ACI that it seems is what you are trying to do. We have a get started guide available at https://docs.bitnami.com/azure/get-started-aci/ Note you can specify the environment variables for the container to specify the database parameters via "--environment-variables".

On the other hand, it is possible to deploy the Joomla! container through a Helm Chart on top of AKS https://docs.bitnami.com/azure/get-started-aks/ 

Could you please add more info about how you are deploying the container and the log you are getting?

**Comment by CodeOfConduct** [comment]
Hi Beltran,

 

Thank you for your reply. Following your suggestion, I read your example-based starter guide at  <https://docs.bitnami.com/azure/get-started-aci/> https://docs.bitnami.com/azure/get-started-aci/. Unfortunately, it seems that neither of the two examples are particularly relevant to the deployment of the Bitnami Joomla/PHP Docker image in Azure. The 1st example, the DokuWiki, refers to an application that does not, unlike Jooma, use a database and the second one, the Wordpress example, requires the Bitnami ACI to be downloaded from Github. However, at https://github.com/bitnami-labs/aci-templates I only found 2 ACI templates: Wordpress and Jenkins. Does Bitnami have a Joomla 3.9.19/PHP 7.3 ACI template? If so, could you please let me have a link to it?

 

I am coming back to the reason for opening this issue: I have not (yet) found instructions for the installation and configuration of the Bitnami Docker image for Joomla / PHP that is made available in the Azure Market Place. Could you please refer me to them?

 

Regarding AKS: I am not familiar with that and would rather stay with Docker, which - after all - is the container type of your image in the Azure Market Place.

 

Regarding the environment variables: I have, as I outlined in steps 7 and 8 of this issue, specified the connection string under the heading “Environment variables” in the Azure Portal. I am aware that you referred to a CLI command in your reply rather than the portal. If the installation and configuration of the Bitnami image / ACI can only be done via the CLI, could you please let me know and send me a link to the full set of commands to ensure that I don’t miss anything. 

 

Once I have a clear set of instructions, which would be of benefit to anyone who wishes to install your Joomla / PHP Docker image, I should be able to get the installation done successfully. If I still hit problems, I’ll gladly send you logs. Without such instructions, we could be going back and forth for a while… which I think is in neither of our interests…

 

Thanks and regards,

 

Carl

 

 

Von: Beltran [mailto:notifications@github.com] 
Gesendet: Dienstag, 16. Juni 2020 12:40
An: bitnami/bitnami-docker-joomla <bitnami-docker-joomla@noreply.github.com>
Cc: codeOfconduct <carl@1sight.com>; Mention <mention@noreply.github.com>
Betreff: Re: [bitnami/bitnami-docker-joomla] Cannot create Azure Web App based on Bitnami Joomla 3.9.19 Docker image (#71)

 

Hi  <https://github.com/CodeOfConduct> @CodeOfConduct,

There are different ways to deploy the Container in Azure. One of them is using ACI that it seems is what you are trying to do. We have a get started guide available at  <https://docs.bitnami.com/azure/get-started-aci/> https://docs.bitnami.com/azure/get-started-aci/ Note you can specify the environment variables for the container to specify the database parameters via "--environment-variables".

On the other hand, it is possible to deploy the Joomla! container through a Helm Chart on top of AKS  <https://docs.bitnami.com/azure/get-started-aks/> https://docs.bitnami.com/azure/get-started-aks/

Could you please add more info about how you are deploying the container and the log you are getting?

**Comment by beltran-rubo** [comment]
Hi @CodeOfConduct 

The default approaches to deploy those container images right now are: using a "docker-compose" file or using a "helm chart" template for Kubernetes. Those are the current approaches we are testing and support to make sure the containers are working properly.

In your case you are trying to deploy the container using ACI. We do not have templates (like the WordPress one) for that platform but it is possible to deploy it. The example we use uses Dokuwiki that does not use any database, but you can specify your database connection via environment variables:

```
MARIADB_HOST=
MARIADB_ROOT_USER=
MARIADB_ROOT_PASSWORD=
```

Those are the instructions to deploy the container on ACI, we do not have a specific guide for Joomla! container using a remote data specifically, sorry about that. We are happy to help if you find any errors in the logs.

**Comment by CodeOfConduct** [comment]
Hi Beltran,

Thank you for the clear reply. I have now had the chance to follow the instructions for deployment of the Bitnami Joomla image via ACLI by adapting the "az container create" command speficied in the instructions for the dokuwiki container and taking the image from an ACR. The ACI was created successfully, but the container log reveals that subsequently it hangs when attempting to connect to the database:

[0m
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing joomla
mysql-c INFO  Trying to connect to MySQL server
 
I am a little surprised to see that apparently a connection is attempted to a MySQL server, because the documentation for the image refers to a MariaDB database and I have therefore created the database on an Azure Database for MariaDB server using dbForge Studio for mySQL. I have configured the MariaDB server’s access security as follows: Allow access to Azure services = Yes, Enforce SSL connection = Disabled.

Also, could you please let me know:

a)	what values have been set for upload_max_filesize and post_max_size
b)	whether installation of multiple languages and the activation of the multilingual feature have been preconfigured

in Bitnami’s Joomla image? These 2 points are important to me to decide whether to try the docker-compose route, because if the image does not have a least point b) built-in, there is little point for me in continuing with it, as I work mostly with multilingual Joomla sites.

I hope this request does not exceed the support that you offered with logs in case of problems.

**Comment by beltran-rubo** [comment]
Hi,

It is only a log message, it support both servers MySQL and MariaDB. The default options for PHP are:

```
upload_max_filesize = 40M
post_max_size = 40M
```

We do not preconfigure multiple languages but it is something you can do from the admin panel. Give a try a let us know if that works for you.

**Comment by CodeOfConduct** [comment]
@beltran-rubo Maybe the following error message, i.e. the last 2 lines of the log from the ACI deployment, will shed some light on what the issue is: 

> mysql-c INFO  Trying to connect to MySQL server
> Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries

I would expect the ACI to connect to the host that I have defined in the environmental variables for Joomla (i.e. JOOMLA_DB_HOST) to appear before the port 3306, not "mariadb". Could it be that "mariadb" is hard-coded into Bitnami's image, as I have not defined it anywhere=?

**Comment by marcosbc** [comment]
@CodeOfConduct Currently mariadb is hardcoded as the default database name. To set a different value, you need to specify the `JOOMLA_DATABASE_HOST` environment variable as you can see in [the provided `docker-compose.yml` file](https://raw.githubusercontent.com/bitnami/bitnami-docker-joomla/master/docker-compose.yml).

**Comment by CodeOfConduct** [comment]
@marcosbc: Thanks for the quick reply. I think you mean mariadb is hard coded as the host / database server (rather than database) name. However, as Azure does not (or did not recently) support the docker-compose command, it seems that I have to generate the Bitnami Docker image outside Azure in order to then deploy it to an Azure Container instance with the db host name that I have configured in Azure (rather than mariadb). I assumed that I could use the Bitnami Joomla Docker image directly in Azure (as it is made available in the Azure Market Place) without having to create a new one using docker-compose - or have I overlooked something?

**Comment by marcosbc** [comment]
You should be able to set environment variables to the deployed Docker container in Azure Container Service. For the CLI, check this page: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-environment-variables

**Comment by CodeOfConduct** [comment]
Thanks, @marcosbc. It worked after changing all 4 environmental variables from the _DB_ to the _DATABASE_ version and setting the port to 8080. However, I could not find the default Joomla admin user name and password in your documentation (we don't use a VM). Where can I find them?

**Comment by marcosbc** [comment]
@CodeOfConduct If you are using a container, those values are set via environment variables. Find the defaults here: https://github.com/bitnami/bitnami-docker-joomla#user-and-site-configuration
